-- =============== PART 1: CREATE ===============

CREATE SCHEMA IF NOT EXISTS bookstore;
SET search_path TO bookstore, public;


CREATE TABLE IF NOT EXISTS publishers (
    publisher_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_name VARCHAR(100) NOT NULL,
    country VARCHAR(50) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(100) NOT NULL UNIQUE,
    contact_phone VARCHAR(20) NOT NULL UNIQUE,
    supplier_email VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS authors (
    author_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books (
    book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id INT NOT NULL,
    supplier_id INT NOT NULL,
    isbn VARCHAR(13) UNIQUE,
    title VARCHAR(255) NOT NULL,
    price NUMERIC(6, 2) NOT NULL CHECK (price >= 0),
    published_date DATE NOT NULL CHECK (published_date > DATE '2026-01-01'),
    language VARCHAR(30) DEFAULT 'English',
    stock_status VARCHAR(20) DEFAULT 'In stock',
    FOREIGN KEY (publisher_id) REFERENCES publishers(publisher_id) ON DELETE RESTRICT,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS book_author (
    book_id INT NOT NULL,
    author_id INT NOT NULL,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES authors(author_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stores (
    store_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    date_opened DATE
);

CREATE TABLE IF NOT EXISTS employees (
    employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    position VARCHAR(20) NOT NULL CHECK (position IN ('Manager', 'Cashier', 'Consultant', 'Storekeeper')),
    FOREIGN KEY (store_id) REFERENCES stores(store_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS inventory (
    store_id INT NOT NULL,
    book_id INT NOT NULL,
    stock_quantity INT NOT NULL CHECK (stock_quantity >= 0),
    last_restocked TIMESTAMP NOT NULL,
    PRIMARY KEY (store_id, book_id),
    FOREIGN KEY (store_id) REFERENCES stores(store_id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS sales (
    sale_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id INT NOT NULL,
    employee_id INT NOT NULL,
    customer_id INT,
    sale_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tax_rate NUMERIC(3, 2) NOT NULL,
    total_amount NUMERIC(8, 2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('Cash', 'Card', 'Mobile')),
  
  --(GENERATED ALWAYS AS)
	
    tax_paid_amount NUMERIC(8, 2) GENERATED ALWAYS AS (total_amount * tax_rate) STORED,
    FOREIGN KEY (store_id) REFERENCES stores(store_id) ON DELETE RESTRICT,
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id) ON DELETE RESTRICT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE SET NULL
);

-- =============== PART 2: ALTER TABLE ===============

ALTER TABLE books ADD COLUMN IF NOT EXISTS has_audiobook BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE customers ALTER COLUMN email TYPE VARCHAR(255);

ALTER TABLE stores DROP CONSTRAINT IF EXISTS uq_store_city_name;
ALTER TABLE stores ADD CONSTRAINT uq_store_city_name UNIQUE (city, store_name);

ALTER TABLE books ALTER COLUMN language SET DEFAULT 'English';
ALTER TABLE authors ADD COLUMN IF NOT EXISTS is_bestseller BOOLEAN DEFAULT false NOT NULL;

-- =============== PART 3: INSERT ===============


TRUNCATE TABLE sales, inventory, book_author, employees, stores, customers, books, authors, suppliers, publishers RESTART IDENTITY CASCADE;

INSERT INTO publishers (publisher_name, country, contact_phone) VALUES 
('OReilly Media', 'USA', '+1-555-0199'),
('Pearson Education', 'United Kingdom', '+44-20-7946'),
('MMP Books', 'Poland', '+48-22-1234'),
('HarperCollins', 'Canada', '+1-416-5555'),
('Meme Publishers', 'Kazakhstan', '+7-701-7777');

INSERT INTO suppliers (supplier_name, contact_phone, supplier_email) VALUES 
('Global Book Distro', '+1-800-5551', 'info@globaldistro.com'),
('EuroBooks Logistics', '+49-89-1122', 'orders@eurobooks.de'),
('Asia Cargo Books', '+81-3-5555', 'tokyo_ship@asiabooks.jp'),
('Almaty Kitap Trade', '+7-727-3333', 'sales@almatykitap.kz'),
('Delete Supplier Ltd', '+44-11-2222', 'test@delete.com');


INSERT INTO authors (first_name, last_name, email) VALUES 
('Anuar', 'Q', 'anuar.q@cyberpunk.ca'),
('Alizhan', 'M', 'alizhan.m@cleancoder.com'),
('Angsar', 'O', 'angsar.o@horrorzone.com'),
('Elnazar', 'T', 'elnazar.t@lofi.jp'),
('Alikhan', 'B', 'alikhan.b@galaxy.edu');

INSERT INTO books (publisher_id, supplier_id, isbn, title, price, published_date, language) VALUES 
((SELECT publisher_id FROM publishers WHERE publisher_name = 'OReilly Media'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Global Book Distro'), '9780132350884', 'Clean Code', 45.00, '2026-02-10', 'English'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'OReilly Media'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Global Book Distro'), '9780596007126', 'Head First Design Patterns', 49.99, '2026-03-15', 'English'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'HarperCollins'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'EuroBooks Logistics'), '9780441569595', 'Neuromancer', 15.50, '2026-01-05', 'English'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'HarperCollins'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'EuroBooks Logistics'), '9780441117734', 'Count Zero', 14.99, '2026-01-20', 'English'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'Pearson Education'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Asia Cargo Books'), '9780307387899', 'Norwegian Wood', 19.00, '2026-04-01', 'Japanese'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'Pearson Education'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Asia Cargo Books'), '9781400079278', 'Kafka on the Shore', 22.00, '2026-05-12', 'Japanese'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'MMP Books'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Almaty Kitap Trade'), '9780345339706', 'The Shining', 18.25, '2026-02-25', 'English'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'MMP Books'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Almaty Kitap Trade'), '9780451169532', 'Misery', 17.50, '2026-03-02', 'English'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'Meme Publishers'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Almaty Kitap Trade'), '9780553293357', 'Foundation', 12.00, '2026-01-11', 'Kazakh'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'Meme Publishers'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Almaty Kitap Trade'), '9780553293364', 'Foundation and Empire', 12.50, '2026-05-20', 'Kazakh'),
((SELECT publisher_id FROM publishers WHERE publisher_name = 'OReilly Media'), (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Delete Supplier Ltd'), '9780000000000', 'Draft Book Unreleased', 0.00, '2026-01-02', 'English');

INSERT INTO book_author (book_id, author_id) VALUES 
((SELECT book_id FROM books WHERE title = 'Clean Code'), (SELECT author_id FROM authors WHERE last_name = 'M')),
((SELECT book_id FROM books WHERE title = 'Head First Design Patterns'), (SELECT author_id FROM authors WHERE last_name = 'M')),
((SELECT book_id FROM books WHERE title = 'Neuromancer'), (SELECT author_id FROM authors WHERE last_name = 'Q')), 
((SELECT book_id FROM books WHERE title = 'Count Zero'), (SELECT author_id FROM authors WHERE last_name = 'Q')),
((SELECT book_id FROM books WHERE title = 'The Shining'), (SELECT author_id FROM authors WHERE last_name = 'O')), 
((SELECT book_id FROM books WHERE title = 'Norwegian Wood'), (SELECT author_id FROM authors WHERE last_name = 'T')), -- Книга Элназара
((SELECT book_id FROM books WHERE title = 'Foundation'), (SELECT author_id FROM authors WHERE last_name = 'B'));

INSERT INTO stores (store_name, city, date_opened) VALUES 
('Grand Book Center', 'Atyrau', '2026-01-15'),
('Cyberpunk Corner', 'Almaty', '2026-02-10'),
('Capital Reads', 'Astana', '2026-03-01'),
('Old Town Books', 'Shymkent', '2026-01-20'),
('Airport Transit Shop', 'Atyrau', '2026-04-05');


INSERT INTO employees (store_id, first_name, last_name, position) VALUES 
((SELECT store_id FROM stores WHERE store_name = 'Grand Book Center' AND city = 'Atyrau'), 'Utezhan', 'Q', 'Manager'),
((SELECT store_id FROM stores WHERE store_name = 'Grand Book Center' AND city = 'Atyrau'), 'Nurbol', 'Q', 'Cashier'),
((SELECT store_id FROM stores WHERE store_name = 'Cyberpunk Corner' AND city = 'Almaty'), 'Kolya', 'K', 'Storekeeper'),
((SELECT store_id FROM stores WHERE store_name = 'Capital Reads' AND city = 'Astana'), 'David', 'D', 'Consultant'),
((SELECT store_id FROM stores WHERE store_name = 'Old Town Books' AND city = 'Shymkent'), 'Askar', 'S', 'Cashier');


INSERT INTO customers (first_name, last_name, email, phone) VALUES 
('Alizhan', 'Zholzhanov', 'alizhan.m@email.com', '+7-702-1111'),
('Nurik', 'kuanyshkali', 'nurik.s@email.com', '+7-705-2222'),
('Samat', 'Saparov', 'samat@email.kz', '+7-777-8888'),
('Rassul', 'orazakhai', 'rassula@me.com', '+0-000-0000');

INSERT INTO inventory (store_id, book_id, stock_quantity, last_restocked)
SELECT s.store_id, b.book_id, 30, '2026-05-01 10:00:00'
FROM stores s
CROSS JOIN books b
WHERE (s.city = 'Atyrau' AND b.title IN ('Clean Code', 'Head First Design Patterns', 'The Shining', 'Foundation'))
   OR (s.city = 'Almaty' AND b.title IN ('Neuromancer', 'Count Zero', 'Kafka on the Shore'))
   OR (s.city = 'Astana' AND b.title IN ('Clean Code', 'Norwegian Wood', 'Foundation and Empire', 'Misery'));


INSERT INTO sales (store_id, employee_id, customer_id, tax_rate, total_amount, payment_method) VALUES 
((SELECT store_id FROM stores WHERE store_name = 'Grand Book Center' AND city = 'Atyrau'), (SELECT employee_id FROM employees WHERE first_name = 'Utezhan' AND last_name = 'Q'), (SELECT customer_id FROM customers WHERE email = 'alizhan.m@email.com'), 0.12, 95.00, 'Cash'),
((SELECT store_id FROM stores WHERE store_name = 'Grand Book Center' AND city = 'Atyrau'), (SELECT employee_id FROM employees WHERE first_name = 'Nurbol' AND last_name = 'Q'), (SELECT customer_id FROM customers WHERE email = 'nurik.s@email.com'), 0.12, 15.50, 'Card'),
((SELECT store_id FROM stores WHERE store_name = 'Cyberpunk Corner' AND city = 'Almaty'), (SELECT employee_id FROM employees WHERE first_name = 'Kolya' AND last_name = 'K'), (SELECT customer_id FROM customers WHERE email = 'nurik.s@email.com'), 0.08, 29.99, 'Card'),
((SELECT store_id FROM stores WHERE store_name = 'Capital Reads' AND city = 'Astana'), (SELECT employee_id FROM employees WHERE first_name = 'David' AND last_name = 'D'), (SELECT customer_id FROM customers WHERE email = 'samat@email.kz'), 0.12, 12.00, 'Cash'),
((SELECT store_id FROM stores WHERE store_name = 'Grand Book Center' AND city = 'Atyrau'), (SELECT employee_id FROM employees WHERE first_name = 'Nurbol' AND last_name = 'Q'), (SELECT customer_id FROM customers WHERE email = 'alizhan.m@email.com'), 0.12, 60.75, 'Card');

-- =============== PART 5: GRANT + REVOKE ===============


ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA bookstore REVOKE SELECT ON TABLES FROM bookstore_readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA bookstore REVOKE INSERT, UPDATE ON TABLES FROM bookstore_writer;


REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA bookstore FROM bookstore_readonly, bookstore_writer;
REVOKE ALL PRIVILEGES ON SCHEMA bookstore FROM bookstore_readonly, bookstore_writer;



DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'bookstore_readonly') THEN
        CREATE ROLE bookstore_readonly;
    END IF;
    
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'bookstore_writer') THEN
        CREATE ROLE bookstore_writer;
    END IF;
END
$$;


GRANT USAGE ON SCHEMA bookstore TO bookstore_readonly;
GRANT USAGE ON SCHEMA bookstore TO bookstore_writer;


ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA bookstore GRANT SELECT ON TABLES TO bookstore_readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA bookstore GRANT INSERT, UPDATE ON TABLES TO bookstore_writer;

-- =============== PART 4: UPDATE + DELETE ===============


UPDATE books 
SET price = price * 0.95 
WHERE supplier_id = (SELECT supplier_id FROM suppliers WHERE supplier_name = 'Global Book Distro');


UPDATE books 
SET stock_status = 'Out of stock' 
WHERE book_id IN (
    SELECT ba.book_id 
    FROM book_author ba
    WHERE ba.author_id = (SELECT author_id FROM authors WHERE last_name = 'M')
);


DELETE FROM customers 
WHERE email = 'delete@me.com'
RETURNING customer_id, first_name, last_name, email;